name: Automatically build debug app

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_app:
    name: Auto build debug app
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: gradle


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Perform debug build
        run: ./gradlew assembleDebug

      - name: Upload apk file
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/**.apk